project_id = "iieethejhwfsyzhbweps"

[functions.parse-menu-pdf]
verify_jwt = true

[functions.send-inquiry-notification]
verify_jwt = false

[functions.trigger-github-deploy]
verify_jwt = true

[functions.spell-check-menu]
verify_jwt = true

[functions.update-landingpage-content]
verify_jwt = false

[functions.gsc-sync]
verify_jwt = false

[functions.gsc-aggregate]
verify_jwt = false
